import { InventoryResponse } from "@/types/inventory";

export const mockInventoryList: InventoryResponse = {
  success: true,
  data: [
    {
      id: 1,
      warehouse: { id: 1, name: "Hanoi Warehouse", location: "Hanoi" },
      product: { id: 1, name: "Château Margaux 2015", price: 5_940_000 },
      quantityOnHand: 50,
      safetyStock: 10,
      status: "in_Stock",
      lastUpdatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: 2,
      warehouse: {
        id: 2,
        name: "Ho Chi Minh City Warehouse",
        location: "Ho Chi Minh City",
      },
      product: { id: 2, name: "Bordeaux 2018", price: 3_500_000 },
      quantityOnHand: 120,
      safetyStock: 15,
      status: "in_Stock",
      lastUpdatedAt: "2024-01-02T11:20:00Z",
    },
    {
      id: 3,
      warehouse: { id: 1, name: "Hanoi Warehouse", location: "Hanoi" },
      product: {
        id: 3,
        name: "Château Lafite Rothschild 2016",
        price: 12_800_000,
      },
      quantityOnHand: 8,
      safetyStock: 10,
      status: "low_Stock",
      lastUpdatedAt: "2024-01-03T09:10:00Z",
    },
    {
      id: 4,
      warehouse: { id: 3, name: "Da Nang Warehouse", location: "Da Nang" },
      product: { id: 4, name: "Barolo DOCG 2017", price: 4_700_000 },
      quantityOnHand: 0,
      safetyStock: 5,
      status: "out_Of_Stock",
      lastUpdatedAt: "2024-01-04T13:50:00Z",
    },
    {
      id: 5,
      warehouse: {
        id: 2,
        name: "Ho Chi Minh City Warehouse",
        location: "Ho Chi Minh City",
      },
      product: { id: 5, name: "Brunello di Montalcino 2016", price: 3_900_000 },
      quantityOnHand: 34,
      safetyStock: 10,
      status: "in_Stock",
      lastUpdatedAt: "2024-01-05T16:00:00Z",
    },
    {
      id: 6,
      warehouse: { id: 1, name: "Hanoi Warehouse", location: "Hanoi" },
      product: { id: 6, name: "Penfolds Grange 2019", price: 6_300_000 },
      quantityOnHand: 5,
      safetyStock: 10,
      status: "low_Stock",
      lastUpdatedAt: "2024-01-06T14:00:00Z",
    },
    {
      id: 7,
      warehouse: {
        id: 2,
        name: "Ho Chi Minh City Warehouse",
        location: "Ho Chi Minh City",
      },
      product: { id: 7, name: "Opus One 2018", price: 9_200_000 },
      quantityOnHand: 60,
      safetyStock: 20,
      status: "in_Stock",
      lastUpdatedAt: "2024-01-07T12:30:00Z",
    },
    {
      id: 8,
      warehouse: { id: 3, name: "Da Nang Warehouse", location: "Da Nang" },
      product: {
        id: 8,
        name: "Caymus Cabernet Sauvignon 2020",
        price: 3_200_000,
      },
      quantityOnHand: 18,
      safetyStock: 10,
      status: "in_Stock",
      lastUpdatedAt: "2024-01-08T08:10:00Z",
    },
    {
      id: 9,
      warehouse: {
        id: 2,
        name: "Ho Chi Minh City Warehouse",
        location: "Ho Chi Minh City",
      },
      product: {
        id: 9,
        name: "Concha y Toro Don Melchor 2019",
        price: 2_700_000,
      },
      quantityOnHand: 0,
      safetyStock: 10,
      status: "out_Of_Stock",
      lastUpdatedAt: "2024-01-09T10:45:00Z",
    },
    {
      id: 10,
      warehouse: { id: 1, name: "Hanoi Warehouse", location: "Hanoi" },
      product: { id: 10, name: "Trapiche Malbec 2021", price: 950_000 },
      quantityOnHand: 200,
      safetyStock: 20,
      status: "in_Stock",
      lastUpdatedAt: "2024-01-10T15:00:00Z",
    },
  ],
};
