import { InventoryLogResponse } from "@/types/inventoryLog";

export const mockInventoryLogs: InventoryLogResponse = {
  success: true,
  data: [
    {
      id: 1,
      warehouse: "Kho Hà Nội",
      product: "Château Margaux 2015",
      type: "IN",
      quantity: 50,
      user: "Nguyễn Văn A",
      note: "Nhập hàng từ nhà cung cấp ABC",
      created_at: "2024-01-15T10:30:00Z",
    },
    {
      id: 2,
      warehouse: "Kho TP.HCM",
      product: "Bordeaux 2018",
      type: "OUT",
      quantity: 20,
      user: "Trần Thị B",
      note: "Xuất hàng cho đơn #ORD-001",
      created_at: "2024-01-15T14:20:00Z",
    },
    {
      id: 3,
      warehouse: "Kho Hà Nội",
      product: "Château Lafite Rothschild 2016",
      type: "IN",
      quantity: 30,
      user: "Nguyễn Văn A",
      note: "Nhập bổ sung tồn kho",
      created_at: "2024-01-16T09:15:00Z",
    },
    {
      id: 4,
      warehouse: "Kho Đà Nẵng",
      product: "Barolo DOCG 2017",
      type: "ADJUST",
      quantity: -5,
      user: "Lê Văn C",
      note: "Điều chỉnh do kiểm kê phát hiện thiếu",
      created_at: "2024-01-16T11:45:00Z",
    },
    {
      id: 5,
      warehouse: "Kho TP.HCM",
      product: "Brunello di Montalcino 2016",
      type: "OUT",
      quantity: 15,
      user: "Trần Thị B",
      note: "Xuất hàng cho đơn #ORD-002",
      created_at: "2024-01-17T08:30:00Z",
    },
    {
      id: 6,
      warehouse: "Kho Hà Nội",
      product: "Penfolds Grange 2019",
      type: "RETURN",
      quantity: 3,
      user: "Nguyễn Văn A",
      note: "Khách hàng trả hàng - lỗi vận chuyển",
      created_at: "2024-01-17T15:20:00Z",
    },
    {
      id: 7,
      warehouse: "Kho TP.HCM",
      product: "Opus One 2018",
      type: "IN",
      quantity: 40,
      user: "Trần Thị B",
      note: "Nhập hàng mới từ NCC XYZ",
      created_at: "2024-01-18T10:00:00Z",
    },
    {
      id: 8,
      warehouse: "Kho Đà Nẵng",
      product: "Caymus Cabernet Sauvignon 2020",
      type: "OUT",
      quantity: 10,
      user: "Lê Văn C",
      note: "Xuất hàng cho đơn #ORD-003",
      created_at: "2024-01-18T13:45:00Z",
    },
    {
      id: 9,
      warehouse: "Kho TP.HCM",
      product: "Concha y Toro Don Melchor 2019",
      type: "IN",
      quantity: 25,
      user: "Trần Thị B",
      note: "Nhập bổ sung do hết hàng",
      created_at: "2024-01-19T09:30:00Z",
    },
    {
      id: 10,
      warehouse: "Kho Hà Nội",
      product: "Trapiche Malbec 2021",
      type: "ADJUST",
      quantity: 10,
      user: "Nguyễn Văn A",
      note: "Điều chỉnh sau kiểm kê - phát hiện thừa",
      created_at: "2024-01-19T16:00:00Z",
    },
    {
      id: 11,
      warehouse: "Kho Hà Nội",
      product: "Rioja Gran Reserva 2015",
      type: "OUT",
      quantity: 8,
      user: "Nguyễn Văn A",
      note: "Xuất hàng cho đơn #ORD-004",
      created_at: "2024-01-20T11:20:00Z",
    },
    {
      id: 12,
      warehouse: "Kho TP.HCM",
      product: "Château Margaux 2015",
      type: "IN",
      quantity: 60,
      user: "Trần Thị B",
      note: "Nhập hàng đợt mới",
      created_at: "2024-01-20T14:30:00Z",
    },
  ],
};
