import { InventoryLogResponse } from "@/types/inventoryLog";

export const mockInventoryLogs: InventoryLogResponse = {
  success: true,
  data: [
    {
      id: 1,
      warehouse: "Hanoi Warehouse",
      product: "Château Margaux 2015",
      type: "IN",
      quantity: 50,
      user: "Nguyễn Văn A",
      note: "Received from supplier ABC",
      created_at: "2024-01-15T10:30:00Z",
    },
    {
      id: 2,
      warehouse: "Ho Chi Minh City Warehouse",
      product: "Bordeaux 2018",
      type: "OUT",
      quantity: 20,
      user: "Trần Thị B",
      note: "Shipped for order #ORD-001",
      created_at: "2024-01-15T14:20:00Z",
    },
    {
      id: 3,
      warehouse: "Hanoi Warehouse",
      product: "Château Lafite Rothschild 2016",
      type: "IN",
      quantity: 30,
      user: "Nguyễn Văn A",
      note: "Restocked inventory",
      created_at: "2024-01-16T09:15:00Z",
    },
    {
      id: 4,
      warehouse: "Da Nang Warehouse",
      product: "Barolo DOCG 2017",
      type: "ADJUST",
      quantity: -5,
      user: "Lê Văn C",
      note: "Adjustment due to shortage found in stocktaking",
      created_at: "2024-01-16T11:45:00Z",
    },
    {
      id: 5,
      warehouse: "Ho Chi Minh City Warehouse",
      product: "Brunello di Montalcino 2016",
      type: "OUT",
      quantity: 15,
      user: "Trần Thị B",
      note: "Shipped for order #ORD-002",
      created_at: "2024-01-17T08:30:00Z",
    },
    {
      id: 6,
      warehouse: "Hanoi Warehouse",
      product: "Penfolds Grange 2019",
      type: "RETURN",
      quantity: 3,
      user: "Nguyễn Văn A",
      note: "Customer returned – shipping damage",
      created_at: "2024-01-17T15:20:00Z",
    },
    {
      id: 7,
      warehouse: "Ho Chi Minh City Warehouse",
      product: "Opus One 2018",
      type: "IN",
      quantity: 40,
      user: "Trần Thị B",
      note: "New stock received from supplier XYZ",
      created_at: "2024-01-18T10:00:00Z",
    },
    {
      id: 8,
      warehouse: "Da Nang Warehouse",
      product: "Caymus Cabernet Sauvignon 2020",
      type: "OUT",
      quantity: 10,
      user: "Lê Văn C",
      note: "Shipped for order #ORD-003",
      created_at: "2024-01-18T13:45:00Z",
    },
    {
      id: 9,
      warehouse: "Ho Chi Minh City Warehouse",
      product: "Concha y Toro Don Melchor 2019",
      type: "IN",
      quantity: 25,
      user: "Trần Thị B",
      note: "Restocked due to sold out",
      created_at: "2024-01-19T09:30:00Z",
    },
    {
      id: 10,
      warehouse: "Hanoi Warehouse",
      product: "Trapiche Malbec 2021",
      type: "ADJUST",
      quantity: 10,
      user: "Nguyễn Văn A",
      note: "Adjustment after stocktaking – found excess",
      created_at: "2024-01-19T16:00:00Z",
    },
    {
      id: 11,
      warehouse: "Hanoi Warehouse",
      product: "Rioja Gran Reserva 2015",
      type: "OUT",
      quantity: 8,
      user: "Nguyễn Văn A",
      note: "Shipped for order #ORD-004",
      created_at: "2024-01-20T11:20:00Z",
    },
    {
      id: 12,
      warehouse: "Ho Chi Minh City Warehouse",
      product: "Château Margaux 2015",
      type: "IN",
      quantity: 60,
      user: "Trần Thị B",
      note: "New shipment received",
      created_at: "2024-01-20T14:30:00Z",
    },
  ],
};
