import { OrderResponse } from "@/types/order";

export const mockOrderList: OrderResponse = {
  success: true,
  data: {
    orders: [
      {
        id: 1,
        order_code: "ORD-20240101-0001",
        customer: {
          id: 1,
          name: "John Doe",
          email: "john@example.com",
        },
        status: 1,
        status_text: "Pending Confirmation",
        payment_status: 1,
        final_amount: 10_692_000,
        created_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 2,
        order_code: "ORD-20240102-0002",
        customer: {
          id: 2,
          name: "Emma Watson",
          email: "emma@example.com",
        },
        status: 2,
        status_text: "Processing",
        payment_status: 2,
        final_amount: 5_300_000,
        created_at: "2024-01-02T10:20:00Z",
      },
      {
        id: 3,
        order_code: "ORD-20240103-0003",
        customer: {
          id: 3,
          name: "David Smith",
          email: "david@example.com",
        },
        status: 3,
        status_text: "Shipping",
        payment_status: 2,
        final_amount: 2_950_000,
        created_at: "2024-01-03T08:45:00Z",
      },
      {
        id: 4,
        order_code: "ORD-20240103-0004",
        customer: {
          id: 4,
          name: "Sophia Miller",
          email: "sophia@example.com",
        },
        status: 4,
        status_text: "Completed",
        payment_status: 3,
        final_amount: 7_890_000,
        created_at: "2024-01-03T14:10:00Z",
      },
      {
        id: 5,
        order_code: "ORD-20240104-0005",
        customer: {
          id: 5,
          name: "Lucas Nguyen",
          email: "lucas@example.com",
        },
        status: 5,
        status_text: "Cancelled",
        payment_status: 1,
        final_amount: 0,
        created_at: "2024-01-04T09:00:00Z",
      },
      {
        id: 6,
        order_code: "ORD-20240105-0006",
        customer: {
          id: 6,
          name: "Olivia Brown",
          email: "olivia@example.com",
        },
        status: 2,
        status_text: "Processing",
        payment_status: 2,
        final_amount: 4_500_000,
        created_at: "2024-01-05T11:30:00Z",
      },
      {
        id: 7,
        order_code: "ORD-20240106-0007",
        customer: {
          id: 7,
          name: "Michael Johnson",
          email: "michael@example.com",
        },
        status: 1,
        status_text: "Pending Confirmation",
        payment_status: 1,
        final_amount: 1_980_000,
        created_at: "2024-01-06T13:50:00Z",
      },
      {
        id: 8,
        order_code: "ORD-20240107-0008",
        customer: {
          id: 8,
          name: "Ava Martinez",
          email: "ava@example.com",
        },
        status: 4,
        status_text: "Completed",
        payment_status: 3,
        final_amount: 6_200_000,
        created_at: "2024-01-07T16:40:00Z",
      },
      {
        id: 9,
        order_code: "ORD-20240108-0009",
        customer: {
          id: 9,
          name: "Daniel Lee",
          email: "daniel@example.com",
        },
        status: 3,
        status_text: "Shipping",
        payment_status: 2,
        final_amount: 3_750_000,
        created_at: "2024-01-08T09:30:00Z",
      },
      {
        id: 10,
        order_code: "ORD-20240109-0010",
        customer: {
          id: 10,
          name: "Mia Davis",
          email: "mia@example.com",
        },
        status: 4,
        status_text: "Completed",
        payment_status: 3,
        final_amount: 8_550_000,
        created_at: "2024-01-09T10:00:00Z",
      }
    ],
    pagination: {
      current_page: 1,
      total_pages: 10,
    },
  },
};
